### ISSUE TITLE
Compilation fails on Alpine for 0.1.4, works on 0.1.3

### ISSUE THREAD

**Issue by mirosval** [rust-lang-nursery/mdBook#644]
I have the following Dockerfile, when I run with `MDBOOK_VERSION=0.1.4` it fails with the below error. When I run with `0.1.3` it compiles w/o problems:

```
FROM alpine:3.7

ARG MDBOOK_VERSION

RUN apk add --no-cache --virtual .build-dependencies \
        gcc \
        musl-dev \
        make \
        rust \
        cargo && \
    cargo install mdbook --vers ${MDBOOK_VERSION} && \
    mv /root/.cargo/bin/mdbook /usr/bin/mdbook && \
    rm -rf /root/.cargo && \
    apk del .build-dependencies && \
    apk add --no-cache libgcc
```
Error:
```
00:01:33.527    Compiling same-file v1.0.2
00:01:33.527    Compiling bitflags v0.9.1
00:01:33.528    Compiling winapi-build v0.1.1
00:01:33.528    Compiling traitobject v0.1.0
00:01:33.785    Compiling unicode-normalization v0.1.5
00:01:34.042 error[E0599]: no method named `hash` found for type `*const str` in the current scope
00:01:34.042    --> root/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.6/src/iterators/pair.rs:250:36
00:01:34.042     |
00:01:34.042 250 |         (self.input as *const str).hash(state);
00:01:34.043     |                                    ^^^^
00:01:34.043     |
00:01:34.043     = note: the method `hash` exists but the following trait bounds were not satisfied:
00:01:34.043             `*const str : std::hash::Hash`
00:01:34.043 
00:01:34.044 error[E0599]: no method named `hash` found for type `*const str` in the current scope
00:01:34.044    --> root/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.6/src/iterators/pairs.rs:162:36
00:01:34.044     |
00:01:34.044 162 |         (self.input as *const str).hash(state);
00:01:34.045     |                                    ^^^^
00:01:34.045     |
00:01:34.045     = note: the method `hash` exists but the following trait bounds were not satisfied:
00:01:34.045             `*const str : std::hash::Hash`
00:01:34.045 
00:01:34.045 error[E0599]: no method named `eq_ignore_ascii_case` found for type `&str` in the current scope
00:01:34.045    --> root/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.6/src/position.rs:354:23
00:01:34.045     |
00:01:34.045 354 |                 slice.eq_ignore_ascii_case(string)
00:01:34.046     |                       ^^^^^^^^^^^^^^^^^^^^
00:01:34.046     |
00:01:34.047     = help: items from traits can only be used if the trait is in scope
00:01:34.047     = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
00:01:34.047             candidate #1: `use std::ascii::AsciiExt;`
00:01:34.047 
00:01:34.048 error[E0599]: no method named `hash` found for type `*const str` in the current scope
00:01:34.048    --> root/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.6/src/position.rs:641:36
00:01:34.049     |
00:01:34.049 641 |         (self.input as *const str).hash(state);
00:01:34.049     |                                    ^^^^
00:01:34.050     |
00:01:34.050     = note: the method `hash` exists but the following trait bounds were not satisfied:
00:01:34.050             `*const str : std::hash::Hash`
00:01:34.050 
00:01:34.051 error[E0599]: no method named `hash` found for type `*const str` in the current scope
00:01:34.051    --> root/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.6/src/span.rs:191:36
00:01:34.051     |
00:01:34.051 191 |         (self.input as *const str).hash(state);
00:01:34.051     |                                    ^^^^
00:01:34.051     |
00:01:34.052     = note: the method `hash` exists but the following trait bounds were not satisfied:
00:01:34.052             `*const str : std::hash::Hash`
00:01:34.052 
00:01:34.052 error: aborting due to 5 previous errors
00:01:34.052 
00:01:34.312 error: Could not compile `pest`.
00:01:34.312 warning: build failed, waiting for other jobs to finish...
00:01:46.492 error: failed to compile `mdbook v0.1.4`, intermediate artifacts can be found at `/tmp/cargo-install.PPZnVkEbIwU8`
00:01:46.492 
00:01:46.492 Caused by:
00:01:46.492   build failed
```

**Comment by Michael-F-Bryan** [comment]
Hmm... What version of Rust do you have installed? It looks like when we updated the handlebars version it also updated `pest` (the library it uses for parsing templates).

**Comment by Michael-F-Bryan** [comment]
This seems to be a duplicate of pest-parser/pest#190, so there's not much `mdbook` can do.
